name: CI

on:
    pull_request:
        types: 
            - opened
            - synchronize
            - reopened

jobs:
    pipeline:
        uses: DivyanshModi25/cicd-pipeline/.github/workflows/clone.yml@main
        secrets: inherit
        