name: PR pipeline

on:
    pull_request:
        types: 
            - opened
            - synchronize
            - reopened

permissions:
    contents: read
    security-events: write

jobs:
    pipeline:
        uses: DivyanshModi25/cicd-pipeline/.github/workflows/ci.yml@main
        
        with:
            python-version: '3.12'
            app_directory: "."
        
        secrets: inherit
        